name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      # 1. ОБЯЗАТЕЛЬНО: Скачиваем код репозитория
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Важно для правильного определения "Нового кода" в Sonar

      # 4. Устанавливаем правильный сканер для .NET (глобально)
      - name: Install SonarCloud scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner

      # 5. Анализ: BEGIN -> BUILD -> END
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.INMARKETSONAR }}
        run: |
          # Запуск сканера
          dotnet-sonarscanner begin /k:"${{ vars.SONAR_PROJECT_KEY }}" /o:"${{ vars.SONAR_ORGANIZATION_KEY }}" /d:sonar.token="${{ secrets.INMARKETSONAR }}" /d:sonar.host.url="https://sonarcloud.io"
          
          # Сборка вашего проекта (укажите путь к sln, если он не в корне)
          dotnet build ./ProductService/ProductService.sln
          
          # Отправка отчета
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.INMARKETSONAR }}"